# Generated by Django 4.1.5 on 2023-01-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0002_rename_name_profile_user_alter_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
